// ─── SENES MEDIA · shared data ──────────────────────────────────
window.SENES_DATA = {
  projects: [
    {
      id: "01",
      slug: "ameca",
      name: "AMECA",
      year: "2025",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Responsive Build"],
      color: "#1a1813",
      accent: "#8FA68E",
      description: "Alex's Medical & Educational Clinic in Africa — a UK charity delivering sustainable healthcare initiatives across Malawi. A warm, editorial website built to tell stories and drive support.",
      brief: "AMECA needed a site that could carry both emotional weight and practical fundraising. We built a clean, story-led front-end — full-bleed imagery, generous type, and clear calls to action — fully responsive from desktop down to phone, so supporters can read, watch, and give from anywhere.",
      website: "https://www.ameca.org.uk",
      cover: "assets/portfolio/ameca/1.jpg",
      images: [
        { src: "assets/portfolio/ameca/1.jpg", caption: "Homepage — In Memory of Alex feature & video", aspect: "16/10" },
        { src: "assets/portfolio/ameca/2.jpg", caption: "About Us — story and ethos", aspect: "16/10" },
        { src: "assets/portfolio/ameca/3.jpg", caption: "Zingwangwa Physio Clinic — programme page", aspect: "16/10" },
        { src: "assets/portfolio/ameca/4.jpg", caption: "Mobile — homepage feature", aspect: "16/10" },
        { src: "assets/portfolio/ameca/5.jpg", caption: "Mobile — In Memory of Alex", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "02",
      slug: "central-construction",
      name: "Central Construction",
      year: "2025",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "CMS"],
      color: "#16213a",
      accent: "#D6485B",
      description: "Central Construction Group Limited — a Malawian civil engineering and construction firm. A confident, corporate website spanning road construction, infrastructure, and water systems.",
      brief: "Central Construction needed to look like an industry leader bidding for serious public works. We built a bold navy-and-red corporate site with a strong service architecture, full responsive layouts, and clear contact pathways for tender enquiries.",
      website: "https://www.centralconstruction.mw",
      cover: "assets/portfolio/central/1.jpg",
      images: [
        { src: "assets/portfolio/central/1.jpg", caption: "Homepage — Water & Sanitation hero", aspect: "16/10" },
        { src: "assets/portfolio/central/2.jpg", caption: "Our Services — three-pillar grid", aspect: "16/10" },
        { src: "assets/portfolio/central/3.jpg", caption: "Mobile — welcome & intro", aspect: "16/10" },
        { src: "assets/portfolio/central/4.jpg", caption: "Mobile — services cards", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "03",
      slug: "consol-finance",
      name: "Consol Finance",
      year: "2025",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Brand"],
      color: "#2a0a4a",
      accent: "#A855F7",
      description: "Consol Finance — loans and digital finance for Malawi's professionals, women, and entrepreneurs. A bright, modern fintech platform with loan products and an application flow.",
      brief: "Consol Finance wanted to feel like the friendliest, most modern lender in the market. We built a vivid purple identity, an AI-forward narrative, dedicated loan-product pages, and a contact and application experience — fully responsive across desktop, tablet, and mobile.",
      website: "https://www.consolfinance.com",
      cover: "assets/portfolio/consol/1.jpg",
      images: [
        { src: "assets/portfolio/consol/1.jpg", caption: "Homepage — \"Your Finance\" hero", aspect: "16/10" },
        { src: "assets/portfolio/consol/2.jpg", caption: "Public Service Advantage Loan — product page", aspect: "16/10" },
        { src: "assets/portfolio/consol/3.jpg", caption: "Contact — \"We're Here For You\"", aspect: "16/10" },
        { src: "assets/portfolio/consol/4.jpg", caption: "Mobile — homepage hero", aspect: "16/10" },
        { src: "assets/portfolio/consol/5.jpg", caption: "Mobile — loan product", aspect: "16/10" },
        { src: "assets/portfolio/consol/6.jpg", caption: "Tablet — Civil Servant Loan", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "04",
      slug: "for-equality-africa",
      name: "For Equality Africa",
      year: "2024",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Knowledge Hub"],
      color: "#3a2410",
      accent: "#E8943A",
      description: "For Equality (FE) — a pan-African women's rights organisation working to accelerate progress towards gender equality. A content-rich advocacy site with a knowledge hub and news.",
      brief: "For Equality needed a platform that could hold research, campaigns, and convenings without feeling cluttered. We built a warm, confident site with a dedicated Knowledge Hub, a What We Do architecture, and a News & Insights feed — all responsive and easy for the team to update.",
      website: "https://www.forequalityafrica.org",
      cover: "assets/portfolio/equality/1.jpg",
      images: [
        { src: "assets/portfolio/equality/1.jpg", caption: "Knowledge Hub — resource library", aspect: "16/10" },
        { src: "assets/portfolio/equality/2.jpg", caption: "What We Do — programme pillars", aspect: "16/10" },
        { src: "assets/portfolio/equality/3.jpg", caption: "Homepage & news — multi-screen overview", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "05",
      slug: "kela-securities",
      name: "Kela Securities",
      year: "2024",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Publications"],
      color: "#141414",
      accent: "#C9C9C9",
      description: "Kela Securities — the first non-bank affiliated Equity Derivatives Market Maker in South Africa. A sophisticated monochrome website for an ambitious financial-markets firm.",
      brief: "Kela Securities competes with multinational investment banks, so the site had to feel institutional yet entrepreneurial. We built a restrained black-and-white system with WebGL-style network motifs, a publications/insights feed, and a products architecture — responsive across every device.",
      website: "https://www.kela.co.za",
      cover: "assets/portfolio/kela/1.jpg",
      images: [
        { src: "assets/portfolio/kela/1.jpg", caption: "Homepage — brand statement hero", aspect: "16/10" },
        { src: "assets/portfolio/kela/2.jpg", caption: "Publications / Insights — article grid", aspect: "16/10" },
        { src: "assets/portfolio/kela/3.jpg", caption: "Contact Us — \"build a successful future\"", aspect: "16/10" },
        { src: "assets/portfolio/kela/4.jpg", caption: "Mobile — homepage", aspect: "16/10" },
        { src: "assets/portfolio/kela/5.jpg", caption: "Mobile — Who We Are", aspect: "16/10" },
        { src: "assets/portfolio/kela/6.jpg", caption: "Tablet — Our Products", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "06",
      slug: "mlb-digital",
      name: "MLB Digital",
      year: "2024",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Portfolio"],
      color: "#2a0a0a",
      accent: "#E0483B",
      description: "MLB Digital — a bold creative and digital agency. A dark, high-energy website with a 3D globe hero, portfolio, and full service offering.",
      brief: "MLB Digital's tagline is \"Be Engaging. Be Proactive. Be Revolutionary\" — so the site had to live up to it. We built a dramatic dark interface with a glowing globe hero, a filterable portfolio, and a complete services layout, fully responsive from desktop to tablet to phone.",
      website: "https://www.mlbdigital.co.za",
      cover: "assets/portfolio/mlb-digital/1.jpg",
      images: [
        { src: "assets/portfolio/mlb-digital/1.jpg", caption: "Homepage — globe hero & contact tiles", aspect: "16/10" },
        { src: "assets/portfolio/mlb-digital/2.jpg", caption: "About MLB Digital — intro", aspect: "16/10" },
        { src: "assets/portfolio/mlb-digital/3.jpg", caption: "Our Portfolio — filtered work grid", aspect: "16/10" },
        { src: "assets/portfolio/mlb-digital/4.jpg", caption: "Our Complete Service Offerings — tablet", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "07",
      slug: "mlb-print-studio",
      name: "MLB Print Studio",
      year: "2024",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Booking"],
      color: "#161616",
      accent: "#BBBBBB",
      description: "MLB Print & Content Creation Studio — a creative space for studio shoots, custom printing, and content. A monospace-led, brutalist-leaning site with studio rental and booking.",
      brief: "The print studio needed a site as distinctive as the space itself. We leaned into a monospace, high-contrast layout with strong black blocks, studio-rental rates, a 360 video booth feature, and a booking flow — responsive across desktop, tablet, and mobile.",
      website: "https://www.mlbprintstudio.co.za",
      cover: "assets/portfolio/mlb-studio/1.jpg",
      images: [
        { src: "assets/portfolio/mlb-studio/1.jpg", caption: "Homepage — MLB Print Studio hero", aspect: "16/10" },
        { src: "assets/portfolio/mlb-studio/2.jpg", caption: "About the studio — intro blocks", aspect: "16/10" },
        { src: "assets/portfolio/mlb-studio/3.jpg", caption: "Mobile — Studio Rental & rates", aspect: "16/10" },
        { src: "assets/portfolio/mlb-studio/4.jpg", caption: "Mobile — Our Services", aspect: "16/10" },
        { src: "assets/portfolio/mlb-studio/5.jpg", caption: "Tablet — Custom Printing", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "08",
      slug: "nali-group",
      name: "Nali Group",
      year: "2023",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "E-Commerce"],
      color: "#4a0f0f",
      accent: "#F2C230",
      description: "Nali Group — Malawi's most-loved peri-peri sauce brand, founded in 1974. A bold, appetite-led website celebrating four decades of Malawian heat, shared with the world.",
      brief: "Nali is a heritage brand with serious flavour, so the site had to feel as vivid as the sauce. We built a punchy red-and-yellow experience with floating product bottles, a Scoville-scale explainer, a products showcase, and brand storytelling — fully responsive across desktop and mobile.",
      website: "https://www.naligroup.mw",
      cover: "assets/portfolio/nali/2.jpg",
      images: [
        { src: "assets/portfolio/nali/2.jpg", caption: "Homepage — \"Made with Malawian Heat\"", aspect: "16/10" },
        { src: "assets/portfolio/nali/3.jpg", caption: "Who We Are — Our Story", aspect: "16/10" },
        { src: "assets/portfolio/nali/4.jpg", caption: "Homepage — full scroll with Scoville scale", aspect: "16/10" },
        { src: "assets/portfolio/nali/1.jpg", caption: "Mobile — products, story & Scoville scale", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "09",
      slug: "tobacco-commission",
      name: "Tobacco Commission",
      year: "2025",
      category: "Web Design · Development",
      services: ["Web Design", "Development", "Data Portal"],
      color: "#16301a",
      accent: "#E0A93B",
      description: "The Tobacco Commission — Malawi's tobacco-industry regulator. A clean, authoritative government website spanning services, licensing data, market data, news, and compliance.",
      brief: "The Commission regulates Malawi's most important export crop, so the site had to feel credible and serve real operational needs. We built a green-and-gold institutional design with a clear services architecture, licensing and market-data sections, a news feed, and compliance resources — fully responsive from desktop to tablet to phone.",
      website: "https://www.tc.mw",
      cover: "assets/portfolio/tobacco/1.jpg",
      images: [
        { src: "assets/portfolio/tobacco/1.jpg", caption: "Homepage — \"Our Tobacco. Our Economy.\" hero", aspect: "16/10" },
        { src: "assets/portfolio/tobacco/2.jpg", caption: "Services — full service grid", aspect: "16/10" },
        { src: "assets/portfolio/tobacco/3.jpg", caption: "News — industry updates feed", aspect: "16/10" },
        { src: "assets/portfolio/tobacco/4.jpg", caption: "Mobile — Our Mission & services", aspect: "16/10" }
      ],
      featured: true
    },
    {
      id: "10",
      slug: "goldman-partners",
      name: "Goldman & Partners",
      year: "2025",
      category: "Brand · Web",
      services: ["Identity", "Web Design", "Print Collateral"],
      color: "#0e3a35",
      accent: "#E07B3F",
      description: "A distinguished full-service law firm in Lilongwe, Malawi. Complete identity system: monogram mark, wordmark, stationery, and a corporate marketing site.",
      brief: "Goldman & Partners came to us as a young law firm in need of the visual gravitas of a firm three times their age — without losing the warmth that set them apart. We built a deep-green and copper identity, a marque-led monogram, and a full collateral system that prints as well in foil as it does on screen.",
      website: "https://www.goldmanmw.com",
      cover: "assets/portfolio/goldman/website.jpg",
      images: [
        { src: "assets/portfolio/goldman/website.jpg", caption: "Marketing site — homepage and case-study templates", aspect: "16/10" },
        { src: "assets/portfolio/goldman/letterhead.jpg", caption: "Letterhead — A4 corporate stationery", aspect: "1/1" },
        { src: "assets/portfolio/goldman/business-cards.jpg", caption: "Business card system — recto and verso", aspect: "4/3" }
      ],
      featured: true
    },
    {
      id: "11",
      slug: "orokam",
      name: "Orokam Foundation",
      year: "2024",
      category: "Brand · Identity",
      services: ["Identity", "Pattern System", "Brand Application"],
      color: "#1a3a1f",
      accent: "#FFD83D",
      description: "A pan-African foundation rooted in cultural heritage. We translated traditional ornament into a contemporary brand mark and an applied pattern system across livery, apparel, and outdoor.",
      brief: "Orokam needed a brand that could hold its own at a continental NGO summit and on a t-shirt at a community event. The mark draws on adinkra-adjacent ornament, executed in a single confident weight. The pattern system reads as both modern and rooted.",
      cover: "assets/portfolio/orokam/02-van-side.jpg",
      images: [
        { src: "assets/portfolio/orokam/02-van-side.jpg", caption: "Vehicle livery — side panel pattern application", aspect: "4/3" },
        { src: "assets/portfolio/orokam/05-van-front.jpg", caption: "Vehicle livery — front and quarter view", aspect: "4/3" },
        { src: "assets/portfolio/orokam/01-cap.jpg", caption: "Headwear — embroidered mark", aspect: "4/3" },
        { src: "assets/portfolio/orokam/03-tshirt.jpg", caption: "T-shirt — chest mark and hem pattern", aspect: "4/3" },
        { src: "assets/portfolio/orokam/04-sweater.jpg", caption: "Sweater — wraparound pattern application", aspect: "4/3" },
        { src: "assets/portfolio/orokam/06-banner.jpg", caption: "Event banner — pattern + logo lockup", aspect: "16/9" }
      ],
      featured: true
    },
    {
      id: "12",
      slug: "uzuri-organics",
      name: "Uzuri Organics",
      year: "2024",
      category: "Brand · Packaging · Campaign",
      services: ["Packaging", "Art Direction", "Social Campaign"],
      color: "#2a2218",
      accent: "#E8C547",
      description: "A South African organic cosmetics line spanning skin, hair, and body. We led packaging across the SKU range and the launch social campaign — editorial typography paired with portraiture.",
      brief: "Uzuri products are gentle. The brand needed to feel gentle too — without disappearing into the noise of the category. We chose a soft, editorial register: serif display, generous white space on packaging, and a campaign built around close, contemplative portraiture.",
      website: "https://www.uzuriorganics.co.za",
      cover: "assets/portfolio/uzuri/07-feel-good.jpg",
      images: [
        { src: "assets/portfolio/uzuri/07-feel-good.jpg", caption: "Brand campaign — \"Look Good, Feel Good.\"", aspect: "1/1" },
        { src: "assets/portfolio/uzuri/03-age.jpg", caption: "Hero campaign — \"Age Flawlessly.\"", aspect: "1/1" },
        { src: "assets/portfolio/uzuri/06-family.jpg", caption: "Brand campaign — \"Join the Uzuri Family.\"", aspect: "1/1" },
        { src: "assets/portfolio/uzuri/08-skin-care.jpg", caption: "Product campaign — Skin Care", aspect: "1/1" },
        { src: "assets/portfolio/uzuri/01-glow-up.jpg", caption: "Glow Up Now — body butter packaging", aspect: "4/3" },
        { src: "assets/portfolio/uzuri/02-glow-pair.jpg", caption: "Glow Up Now — packaging pair, label detail", aspect: "4/3" },
        { src: "assets/portfolio/uzuri/04-curl.png", caption: "Curl Quench — hair butter packaging", aspect: "4/3" },
        { src: "assets/portfolio/uzuri/05-did-you-know.jpg", caption: "Product education — Revitalize & Grow Hair Oil", aspect: "1/1" }
      ],
      featured: true
    },
    {
      id: "13",
      slug: "omulunga-gin",
      name: "Omulunga Gin",
      year: "2023",
      category: "Packaging · Identity",
      services: ["Label Design", "Naming Support", "Copywriting"],
      color: "#2a0e1a",
      accent: "#D63384",
      description: "A small-batch Namibian gin distilled from indigenous Makalani palm fruit. We designed the front- and back-label system and wrote the back-of-bottle voice.",
      brief: "Omulunga is a wild, untamed spirit. Its label needed to feel like the kind of bottle you'd pull off a shelf in Windhoek and take home for a story. We leaned into 19th-century apothecary ornament, then wrote a back label that doesn't take itself too seriously.",
      cover: "assets/portfolio/omulunga/03-front-alt.jpg",
      images: [
        { src: "assets/portfolio/omulunga/03-front-alt.jpg", caption: "Front label — primary lockup", aspect: "3/4" },
        { src: "assets/portfolio/omulunga/04-back-alt.jpg", caption: "Back label — copy + ornament", aspect: "3/4" },
        { src: "assets/portfolio/omulunga/01-front.jpg", caption: "Front label — sister SKU (Ombike)", aspect: "3/4" },
        { src: "assets/portfolio/omulunga/02-back.jpg", caption: "Back label — sister SKU detail", aspect: "3/4" }
      ],
      featured: true
    }
  ],
  services: [
    { num: "01", name: "Graphic Design", blurb: "Strong, memorable brand identities that visually communicate your message.", deliverables: ["Logo design & brand identity", "Corporate profiles & marketing", "Social media graphics", "Advertising & promotional designs", "Infographics & presentations"] },
    { num: "02", name: "Web Development", blurb: "Modern websites that combine functionality, performance, and aesthetics.", deliverables: ["Business & corporate websites", "E-commerce platforms", "Portfolio & media websites", "Website maintenance & optimization", "SEO-friendly development"] },
    { num: "03", name: "Web Applications", blurb: "Custom web applications that improve operational efficiency and support digital services.", deliverables: ["Custom business systems", "Data management platforms", "Online portals & dashboards", "Secure cloud-based applications", "Business automation systems"] },
    { num: "04", name: "Communications", blurb: "We help organizations communicate clearly and effectively with their audiences.", deliverables: ["Corporate communication strategy", "Media relations & press materials", "Content development & storytelling", "Digital communication campaigns", "Brand messaging & PR"] },
    { num: "05", name: "Video & Media Production", blurb: "Visually engaging video content that communicates stories and strengthens brand presence.", deliverables: ["Promotional videos", "Corporate documentaries", "Social media video campaigns", "Event coverage", "Brand storytelling productions"] },
  ],
  process: [
    { num: "01", name: "Discover", weeks: "1–2", blurb: "Stakeholder interviews, audit, competitive landscape, and a written brief we both sign off on." },
    { num: "02", name: "Define", weeks: "1–2", blurb: "Strategy, narrative architecture, and a sketch of the system we'll build inside of." },
    { num: "03", name: "Design", weeks: "3–6", blurb: "Concept, then iteration. Two rounds of high-fidelity, then a frozen master file." },
    { num: "04", name: "Develop", weeks: "3–8", blurb: "Build in parallel with motion direction. Staging from week one. Real content from week three." },
    { num: "05", name: "Deliver", weeks: "1", blurb: "Launch, hand-off, training. Then a 30-day window where the team stays on call." },
  ],
  reviews: [
    { quote: "They translated everything that makes us bold into a website that finally feels like us — fast, dramatic, and impossible to ignore. The globe hero alone gets brought up in every client meeting.", author: "MLB Digital", role: "Digital Agency", company: "", year: "2025" },
    { quote: "We needed a site as distinctive as our studio space. What they delivered is unapologetically us — the booking flow just works and clients comment on it constantly.", author: "MLB Print Studio", role: "Creative & Print Studio", company: "", year: "2024" },
    { quote: "A government platform that's actually clear and credible. Services, licensing, market data, and news all live together without feeling cluttered. Exactly what the industry needed.", author: "Tobacco Commission", role: "Industry Regulator", company: "", year: "2025" },
    { quote: "Bright, modern, and trustworthy — they captured the friendliest lender in the market in one build. Our loan-application traffic climbed from the week we launched.", author: "Consol Finance", role: "Financial Services", company: "", year: "2025" },
    { quote: "Institutional but entrepreneurial — they understood the brief immediately. The site holds its own against the multinational banks we compete with.", author: "Kela Securities", role: "Equity Markets", company: "", year: "2024" },
    { quote: "As vivid as the sauce itself. The site celebrates four decades of heritage and still feels current. Our distributors love sending people to it.", author: "Nali Group", role: "Food & Beverage", company: "", year: "2023" },
    { quote: "A site that carries both emotional weight and practical fundraising. Supporters can read, watch, and give from anywhere — and they do.", author: "AMECA", role: "Healthcare Charity", company: "", year: "2025" },
    { quote: "We look like the industry leader we are. The service architecture is clear and the enquiries we get through the site are far better qualified.", author: "Central Construction", role: "Civil Engineering", company: "", year: "2025" },
  ],
  tools: [
    { group: "Design", items: ["Figma", "Photoshop", "Illustrator", "After Effects", "Cinema 4D"] },
    { group: "Code", items: ["Next.js", "React", "Astro", "GSAP", "Three.js", "Tailwind"] },
    { group: "Stack", items: ["Vercel", "Sanity", "Contentful", "Shopify", "Webflow"] },
    { group: "Method", items: ["Figma to code", "Hand-off via Storybook", "Notion docs", "Linear cycles"] },
  ],
  faqs: [
    { q: "What does a typical engagement look like?", a: "Most projects run 8–14 weeks end-to-end. A standard rhythm is: 2 weeks of discovery and strategy, 4 weeks of design, 4 weeks of build, 1 week of polish and launch. Brand-only work is shorter; platform work is longer." },
    { q: "Do you work with agencies or only direct?", a: "Both. A portion of our work each year is white-labelled through agencies, the rest direct with founders, in-house teams, and creative directors." },
    { q: "How much does a project cost?", a: "Every engagement is scoped to outcomes, so pricing depends on the work. Tell us about your project through the contact form and we'll come back with a tailored proposal." },
    { q: "How do we get a quote?", a: "Send us a brief through the contact form — the more you tell us about your goals and timeline, the more accurate our proposal. We reply within 30 minutes." },
    { q: "Who actually does the work?", a: "Our team. For larger builds we bring in a small bench of trusted collaborators — developers, motion designers, photographers — but we're on the file, in every meeting, and the last set of eyes before launch." },
    { q: "How do you handle revisions?", a: "Two structured rounds at high-fidelity, then a frozen master file. Beyond that, change requests are scoped and agreed up front. Most projects never reach round three." },
    { q: "What's your time-zone situation?", a: "We work asynchronously across multiple time zones. Most projects keep a 4-hour overlap with the client's working hours by default; longer hand-offs are scheduled around your workflow, not ours." },
    { q: "Can you ship a site, not just design one?", a: "Yes. We write production-ready front-end and have shipped platforms with CMS, e-commerce, and motion all running together. For backend-heavy work we partner with vetted development teams." },
  ],
  stats: [
    { value: "10", suffix: "yrs", label: "of practice" },
    { value: "140", suffix: "+", label: "projects shipped" },
    { value: "62", suffix: "", label: "clients & counting" },
    { value: "4", suffix: "", label: "industry awards" },
  ],
  contact: {
    email: "info@senesmedia.com",
    phone: "+265 88 305 3633",
    address: ["SENES Media", "Available worldwide"],
    social: [
      { name: "Instagram", url: "https://www.instagram.com/senesmedia" },
      { name: "LinkedIn", url: "https://www.linkedin.com/company/senes-media/" },
    ],
  },
};
